### ISSUE TITLE
Parallel Execution - TypeError: Cannot read property 'sourceLocation' of undefined

### ISSUE THREAD

**Issue by fescobar** [korobochka/cucumberjs-allure2-reporter#6]
When I tried to run in parallel:
`./node_modules/cucumber/bin/cucumber-js --parallel 5 --format ./path/to/Reporter.js:./dummy.txt`
throws next error:

```
cucumberjs-allure2-reporter/dist/src/CucumberJSAllureReporter.js:179
        if (location.sourceLocation !== undefined && feature.stepMap !== undefined) {
                     ^

TypeError: Cannot read property 'sourceLocation' of undefined
    at Reporter.CucumberJSAllureFormatter.onTestStepStarted (/Users/frank.escobar/Documents/git/cucumberjs-allure2-reporter/dist/src/CucumberJSAllureReporter.js:179:22)
    at emitOne (events.js:116:13)
    at EventEmitter.emit (events.js:211:7)
    at Master.parseSlaveLine (/Users/frank.escobar/Documents/git/cucumberjs-allure2-reporter/node_modules/cucumber/lib/runtime/parallel/master.js:76:33)
    at Interface.<anonymous> (/Users/frank.escobar/Documents/git/cucumberjs-allure2-reporter/node_modules/cucumber/lib/runtime/parallel/master.js:102:15)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

**Comment by korobochka** [comment]
Hi, as far as I understand Cucumber does not support custom formatters with parallel option. I cannot fix this from the reporter side, please vote for this issue:
https://github.com/cucumber/cucumber-js/issues/1038
